### ISSUE TITLE
Collator heading overlaps

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/portal#80] opened 2023-03-14 07:39 UTC
### Describe the bug

On the collator dashboard i see side scroll and the collator heading overlaps other headings

### Reproduction

1. Go to `/collator` on portal
2. Scroll left and right
3. You will see the collator heading overlaps over other heading

### Expected behavior

There should be no overlap of the headings over each other and also no side scroll, ideally the user should be able to see the entire table without scrolling.

### Screenshots

<img width="946" alt="Screenshot 2023-03-14 at 12 59 28 PM" src="https://user-images.githubusercontent.com/52105313/224926828-49635d68-9919-4c3a-98e6-1a1cdd4da907.png">

### Desktop (please complete the following information):

- OS: iOS
- Browser both chrome[111.0.5563.64] and safari[16.1]

**Comment by gonzamontiel** [comment] 2023-03-14 23:25
hey @prayagd, can you please check that after we merged #70 this is still happening?
For me it looks like this in staging:
![Screenshot from 2023-03-15 00 23 52](https://user-images.githubusercontent.com/4713407/225163935-dafeb74c-4e4a-4990-b15e-70977ac6d14c.png)

![Screenshot from 2023-03-15 00 23 25](https://user-images.githubusercontent.com/4713407/225163949-7486dd17-9618-4139-9be7-a2d857b58803.png)

If it still happens, we need to ask someone with MacOS that can reproduce it, @ebma @nejcm ?

**Comment by gonzamontiel** [comment] 2023-03-14 23:29
I didn't mean to close it, let's check if the bug in macOS is still there. Also @prayagd, if it still happens to you, can you edit the title to add a tag like [MacOS] or a label like `macos-only`?

**Comment by ebma** [comment] 2023-03-21 11:37
Can confirm that this can happen. But it only happens when I zoom in to 110%. 
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/6690623/226594633-80e20faf-353c-4219-8846-f7cc1c15c584.png">

I think the problem is actually that the table does not 'responsively' adjust to zooming. Even in 100% zoom (so no zoom at all but the default value), the table is scrollable which I think is a bit annoying. (As you can see on the screenshot the buttons are not entirely visible and I can scroll to the right). I would expect the table to show without scrolling by default but I'm not sure how easy it is to achieve. 
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/6690623/226594977-bd7b96c5-ae71-4b45-96ff-221abf76914b.png">

**Comment by nejcm** [comment] 2023-06-28 17:08
The problem is some css from the daisy lib. It has some table headers set as position sticky.

**Closed** 2023-06-29 11:10 UTC
Labels: type:bug
