### ISSUE TITLE
Fetch swap pools info for Nabla

### ISSUE THREAD

**Issue by nejcm** [pendulum-chain/portal#114] opened 2023-04-26 12:40 UTC
As a 0xAmber user, i should be able to see the details of the swap pools. 

## Acceptance criteria
* On /swap-pools
* In the pools table show the following details
    * Token name
    * Wallet balance of that token
    * My pool amount - Amount deposited in that pool 
    * Pool liabilities - total amount of deposits into the pool + accumulated swap fees for the pool
    * Coverage ratio - % of Total amount currently in the pool/ Total amount deposited in the pool
    * APR - % of Swap fees generated per pool + $PEN rewards

## Technical consideration

For now I don't see a way to read the set of supported swap pools from the contracts. Thus, we would need to hard-code this in the Portal. Another solution would be to add a method that returns this information.

To fetch the information that is clear to me:

* token name
   * call the `asset` function of the swap pool contract
   * this is the address of an ERC20 contract, so call the `name` method of that address
 * wallet balance of that token
   * first fetch the address of the ERC20 token and then call `balanceOf` of that contract specifying the user's address
 * amount deposited in pool:   
   * We can't see the actual amount deposited but we can display the redeemable amount (which is roughly the same but the redeemable amount can be higher because the liquidity provider participated in swap fees).
   * first call the method `balanceOf` of the swap pool contract specifying the address of the user
   * with the return result ("shares") call the method `sharesTargetWorth` specifying "shares" as the argument
   * display the returned value

More info about tasks: https://www.notion.so/0xamber/Amber-Pendulum-portal-7f7a455b95214046ad566be2f9dd83a8

**Comment by prayagd** [comment] 2023-05-11 06:58
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/portal/114?planning-poker) with Zenhub @ebma @gonzamontiel

**Comment by TorstenStueber** [comment] 2023-06-22 17:11
@prayagd what is the definition of 
* Pool liabilities
* Coverage ratio
* APR

**Comment by TorstenStueber** [comment] 2023-06-22 17:19
## Technical refinement

For now I don't see a way to read the set of supported swap pools from the contracts. Thus, we would need to hard-code this in the Portal. Another solution would be to add a method that returns this information.

To fetch the information that is clear to me:
* token name
  * call the `asset` function of the swap pool contract
  * this is the address of an ERC20 contract, so call the `name` method of that address
* wallet balance of that token
  * first fetch the address of the ERC20 token and then call `balanceOf` of that contract specifying the user's address
* amount deposited in pool:
  * We can't see the actual amount deposited but we can display the redeemable amount (which is roughly the same but the redeemable amount can be higher because the liquidity provider participated in swap fees).
  * first call the method `balanceOf` of the swap pool contract specifying the address of the user
  * with the return result ("shares") call the method `sharesTargetWorth` specifying "shares" as the argument
  * display the returned value

**Comment by prayagd** [comment] 2023-06-23 07:25
> @prayagd what is the definition of
> 
> * Pool liabilities
> * Coverage ratio
> * APR

@TorstenStueber Regarding Pool liabilities, coverage ratio i am not aware of those. Need more clarity from the Nabla team.  We can skip APR as the Nabla team is not planning to have any rewards. @nejcm are you aware of these terms or should i follow-up with Andy?

**Comment by TorstenStueber** [comment] 2023-07-13 06:46
I propose: let's remove everything that is not clear to product.

Who comes up with these requirements? Our product team or the Nabla team?

**Comment by nejcm** [comment] 2023-07-13 17:44
So what to keep and what to remove is up to be decided. So the requirements were taken out of the design which was probably inspired by other products.

**Comment by TorstenStueber** [comment] 2023-07-14 09:15
Thanks, understood. However, I do think that the content of the UI should not be defined by design but by us (product) and we would need to understand first what we actually want to display content-wise. Then we can define it (mathematically) and after that it can be integrated by the designer.

So can we do this @prayagd? Otherwise, let's cut them out for now and add them later if we think they are beneficial to users or they expect to see them.

**Comment by nejcm** [comment] 2023-07-16 05:34
I would agree. We should cut for simplicity for now and we can always add later.

**Comment by prayagd** [comment] 2023-07-20 13:20
@TorstenStueber First of all the designs requirements were provided by the Nabla team as they have more context on how the smart contracts will work and what relevant information out of these smart contract should be shown to the end user. The designer has not at all come up with those terms on his own. 

Also totally agree to you about removing the stuff we dont understand and we can eventually add it when needed. For now i have added the meaning of the terms that were unclear.

**Comment by TorstenStueber** [comment] 2023-07-20 14:38
@prayagd If these designs and requirements come from the Nabla team, then of course I assume that they can provide the definitions (and how to extract the data from the contracts). That would also be fine.

**Comment by prayagd** [comment] 2024-03-15 07:34
Closing these older tickets, as these were for the backend work. Currently all the info is displayed

**Closed by prayagd** 2024-03-15 07:34 UTC
