### ISSUE TITLE
Transfer tab not showing new assets

### ISSUE THREAD

**Issue by LeoFraq** [pendulum-chain/portal#164] opened 2023-05-24 14:38 UTC
### Describe the bug

New assets are not properly displayed in the transfer tab (TZS, BRL)

### Reproduction

1. Go to Transfer
2. Scroll down to the table
3. See error if any Tx with never currencies is prsent

### Expected behavior

The tokens are shown by their short-hand

### Screenshots

![image.png](https://images.zenhubusercontent.com/640f1eb404b2a44433611a9f/57addaa8-eedd-4428-be3d-9a7fa503c820)

**Comment by ebma** [comment] 2023-05-24 15:21
This is a duplicate of #158.

**Closed by ebma** 2023-05-24 15:21 UTC
